"""Bulk news catalog (~500 feeds). Core high-frequency sources stay in news_sources.default_sources()."""

from __future__ import annotations

from typing import Dict, List
from urllib.parse import quote

# (source_id, publisher, domain, trust)
SITES: List[tuple] = [
    ("reuters", "Reuters", "reuters.com", 0.90),
    ("apnews", "AP", "apnews.com", 0.88),
    ("afp", "AFP", "afp.com", 0.86),
    ("bloomberg", "Bloomberg", "bloomberg.com", 0.92),
    ("wsj", "WSJ", "wsj.com", 0.90),
    ("ftcom", "Financial Times", "ft.com", 0.90),
    ("economist", "The Economist", "economist.com", 0.86),
    ("nytimes", "NYT", "nytimes.com", 0.86),
    ("washingtonpost", "Washington Post", "washingtonpost.com", 0.84),
    ("latimes", "LA Times", "latimes.com", 0.78),
    ("usatoday", "USA Today", "usatoday.com", 0.70),
    ("politico", "Politico", "politico.com", 0.80),
    ("thehill", "The Hill", "thehill.com", 0.74),
    ("axios", "Axios", "axios.com", 0.78),
    ("npr", "NPR", "npr.org", 0.82),
    ("cnn", "CNN", "cnn.com", 0.72),
    ("cnbc", "CNBC", "cnbc.com", 0.80),
    ("foxbusiness", "Fox Business", "foxbusiness.com", 0.68),
    ("forbes", "Forbes", "forbes.com", 0.70),
    ("businessinsider", "Business Insider", "businessinsider.com", 0.66),
    ("fortunecom", "Fortune", "fortune.com", 0.76),
    ("barrons", "Barron's", "barrons.com", 0.82),
    ("marketwatchcom", "MarketWatch", "marketwatch.com", 0.74),
    ("investopedia", "Investopedia", "investopedia.com", 0.64),
    ("seekingalpha", "Seeking Alpha", "seekingalpha.com", 0.62),
    ("motleyfool", "Motley Fool", "fool.com", 0.58),
    ("benzinga", "Benzinga", "benzinga.com", 0.60),
    ("thestreet", "TheStreet", "thestreet.com", 0.60),
    ("zacks", "Zacks", "zacks.com", 0.58),
    ("tipranks", "TipRanks", "tipranks.com", 0.56),
    ("etfcom", "ETF.com", "etf.com", 0.64),
    ("morningstar", "Morningstar", "morningstar.com", 0.72),
    ("spglobal", "S&P Global", "spglobal.com", 0.84),
    ("moodys", "Moody's", "moodys.com", 0.80),
    ("fitch", "Fitch", "fitchratings.com", 0.80),
    ("imf", "IMF", "imf.org", 0.90),
    ("worldbank", "World Bank", "worldbank.org", 0.88),
    ("bis", "BIS", "bis.org", 0.90),
    ("oecd", "OECD", "oecd.org", 0.86),
    ("wto", "WTO", "wto.org", 0.82),
    ("opecorg", "OPEC", "opec.org", 0.86),
    ("iea", "IEA", "iea.org", 0.86),
    ("eia_gov", "EIA", "eia.gov", 0.90),
    ("whitehouse", "White House", "whitehouse.gov", 0.88),
    ("treasury", "US Treasury", "home.treasury.gov", 0.90),
    ("secgov", "SEC", "sec.gov", 0.95),
    ("cftcgov", "CFTC", "cftc.gov", 0.93),
    ("fdic", "FDIC", "fdic.gov", 0.90),
    ("occ", "OCC", "occ.gov", 0.88),
    ("doj", "DOJ", "justice.gov", 0.86),
    ("ftc", "FTC", "ftc.gov", 0.84),
    ("cisa", "CISA", "cisa.gov", 0.84),
    ("esma", "ESMA", "esma.europa.eu", 0.88),
    ("ecbeuropa", "ECB", "ecb.europa.eu", 0.96),
    ("boengland", "Bank of England", "bankofengland.co.uk", 0.95),
    ("boj_or_jp", "Bank of Japan", "boj.or.jp", 0.92),
    ("rba", "RBA", "rba.gov.au", 0.90),
    ("rbnz", "RBNZ", "rbnz.govt.nz", 0.88),
    ("snb", "SNB", "snb.ch", 0.90),
    ("bundesbank", "Bundesbank", "bundesbank.de", 0.90),
    ("bankofcanada", "Bank of Canada", "bankofcanada.ca", 0.90),
    ("pboc", "PBOC", "pbc.gov.cn", 0.80),
    ("mas_sg", "MAS", "mas.gov.sg", 0.88),
    ("hkma", "HKMA", "hkma.gov.hk", 0.86),
    ("asic", "ASIC", "asic.gov.au", 0.84),
    ("fca_uk", "FCA", "fca.org.uk", 0.88),
    ("bafin", "BaFin", "bafin.de", 0.84),
    ("finra", "FINRA", "finra.org", 0.82),
    ("cme", "CME Group", "cmegroup.com", 0.80),
    ("ice", "ICE", "ice.com", 0.78),
    ("lme", "LME", "lme.com", 0.78),
    ("kitconews", "Kitco", "kitco.com", 0.74),
    ("oilpricecom", "OilPrice", "oilprice.com", 0.78),
    ("miningcom", "Mining.com", "mining.com", 0.70),
    ("fastmarkets", "Fastmarkets", "fastmarkets.com", 0.70),
    ("argusmedia", "Argus Media", "argusmedia.com", 0.72),
    ("platts", "S&P Platts", "spglobal.com/commodityinsights", 0.80),
    ("rigzone", "Rigzone", "rigzone.com", 0.64),
    ("worldoil", "World Oil", "worldoil.com", 0.64),
    ("ogj", "OGJ", "ogj.com", 0.64),
    ("energyintel", "Energy Intel", "energyintel.com", 0.70),
    ("carbonbrief", "Carbon Brief", "carbonbrief.org", 0.70),
    ("goldorg", "World Gold Council", "gold.org", 0.78),
    ("silverinstitute", "Silver Institute", "silverinstitute.org", 0.66),
    ("copperorg", "ICSG", "icsg.org", 0.64),
    ("farmjournal", "Farm Journal", "farmjournal.com", 0.60),
    ("agweb", "AgWeb", "agweb.com", 0.58),
    ("successfulfarming", "Successful Farming", "agriculture.com", 0.58),
    ("coindeskcom", "CoinDesk", "coindesk.com", 0.78),
    ("cointelegraphcom", "Cointelegraph", "cointelegraph.com", 0.72),
    ("theblockco", "The Block", "theblock.co", 0.78),
    ("decryptco", "Decrypt", "decrypt.co", 0.68),
    ("blockworksco", "Blockworks", "blockworks.co", 0.74),
    ("thedefiantio", "The Defiant", "thedefiant.io", 0.74),
    ("dlnewscom", "DL News", "dlnews.com", 0.73),
    ("messari", "Messari", "messari.io", 0.70),
    ("theblockcrypto", "The Block", "theblockcrypto.com", 0.74),
    ("cryptobriefing", "CryptoBriefing", "cryptobriefing.com", 0.58),
    ("newsbtc", "NewsBTC", "newsbtc.com", 0.56),
    ("cryptopotato", "CryptoPotato", "cryptopotato.com", 0.56),
    ("ambcrypto", "AMBCrypto", "ambcrypto.com", 0.54),
    ("coinjournal", "CoinJournal", "coinjournal.net", 0.56),
    ("bitcoinist", "Bitcoinist", "bitcoinist.com", 0.52),
    ("cryptoslatecom", "CryptoSlate", "cryptoslate.com", 0.62),
    ("beincryptocom", "BeInCrypto", "beincrypto.com", 0.60),
    ("coinbasecom", "Coinbase", "coinbase.com", 0.84),
    ("binancecom", "Binance", "binance.com", 0.78),
    ("krakencom", "Kraken", "kraken.com", 0.80),
    ("bitfinex", "Bitfinex", "bitfinex.com", 0.70),
    ("okx", "OKX", "okx.com", 0.70),
    ("bybit", "Bybit", "bybit.com", 0.66),
    ("hyperliquid", "Hyperliquid", "hyperliquid.xyz", 0.70),
    ("ethereumorg", "Ethereum", "ethereum.org", 0.90),
    ("bitcoinorg", "Bitcoin.org", "bitcoin.org", 0.80),
    ("techcrunchcom", "TechCrunch", "techcrunch.com", 0.70),
    ("thevergecom", "The Verge", "theverge.com", 0.66),
    ("wired", "Wired", "wired.com", 0.72),
    ("arstechnicacom", "Ars Technica", "arstechnica.com", 0.70),
    ("engadget", "Engadget", "engadget.com", 0.62),
    ("theinformation", "The Information", "theinformation.com", 0.80),
    ("protocolcom", "Protocol", "protocol.com", 0.68),
    ("semafor", "Semafor", "semafor.com", 0.74),
    ("stratechery", "Stratechery", "stratechery.com", 0.76),
    ("theregister", "The Register", "theregister.com", 0.64),
    ("zdnet", "ZDNet", "zdnet.com", 0.60),
    ("cnet", "CNET", "cnet.com", 0.58),
    ("tomshardware", "Tom's Hardware", "tomshardware.com", 0.58),
    ("anandtech", "AnandTech", "anandtech.com", 0.64),
    ("semianalysis", "SemiAnalysis", "semianalysis.com", 0.74),
    ("digitimes", "Digitimes", "digitimes.com", 0.70),
    ("nikkei", "Nikkei", "asia.nikkei.com", 0.86),
    ("japantimes", "Japan Times", "japantimes.co.jp", 0.74),
    ("scmpcom", "SCMP", "scmp.com", 0.80),
    ("caixin", "Caixin", "caixinglobal.com", 0.80),
    ("globaltimes", "Global Times", "globaltimes.cn", 0.55),
    ("xinhua", "Xinhua", "news.cn", 0.60),
    ("straits", "Straits Times", "straitstimes.com", 0.76),
    ("channelnewsasia", "CNA", "channelnewsasia.com", 0.78),
    ("koreaherald", "Korea Herald", "koreaherald.com", 0.72),
    ("koreajoongang", "Korea JoongAng", "koreajoongangdaily.joins.com", 0.72),
    ("hankyoreh", "Hankyoreh", "hani.co.kr", 0.64),
    ("thehindu", "The Hindu", "thehindu.com", 0.74),
    ("toi", "Times of India", "timesofindia.indiatimes.com", 0.66),
    ("indianexpress", "Indian Express", "indianexpress.com", 0.70),
    ("livemint", "Mint", "livemint.com", 0.74),
    ("economictimes", "Economic Times", "economictimes.indiatimes.com", 0.72),
    ("businessstd", "Business Standard", "business-standard.com", 0.70),
    ("smh", "SMH", "smh.com.au", 0.76),
    ("theage", "The Age", "theage.com.au", 0.74),
    ("afr", "AFR", "afr.com", 0.82),
    ("abcau", "ABC Australia", "abc.net.au", 0.78),
    ("nzherald", "NZ Herald", "nzherald.co.nz", 0.70),
    ("globeandmail", "Globe and Mail", "theglobeandmail.com", 0.80),
    ("nationalpost", "National Post", "nationalpost.com", 0.70),
    ("cbc", "CBC", "cbc.ca", 0.78),
    ("lemonde", "Le Monde", "lemonde.fr", 0.80),
    ("lefigaro", "Le Figaro", "lefigaro.fr", 0.74),
    ("lesechos", "Les Echos", "lesechos.fr", 0.80),
    ("france24", "France24", "france24.com", 0.76),
    ("spiegel", "Der Spiegel", "spiegel.de", 0.80),
    ("faz", "FAZ", "faz.net", 0.80),
    ("handelsblatt", "Handelsblatt", "handelsblatt.com", 0.84),
    ("zeit", "Die Zeit", "zeit.de", 0.76),
    ("elpais", "El Pais", "elpais.com", 0.78),
    ("expansion", "Expansion", "expansion.com", 0.70),
    ("corriere", "Corriere", "corriere.it", 0.74),
    ("repubblica", "La Repubblica", "repubblica.it", 0.72),
    ("ilsole", "Il Sole 24 Ore", "ilsole24ore.com", 0.82),
    ("nrc", "NRC", "nrc.nl", 0.74),
    ("telegraaf", "Telegraaf", "telegraaf.nl", 0.62),
    ("ftnl", "FD", "fd.nl", 0.76),
    ("swissinfo", "SWI", "swissinfo.ch", 0.74),
    ("aftenposten", "Aftenposten", "aftenposten.no", 0.70),
    ("dnse", "Dagens Nyheter", "dn.se", 0.72),
    ("hsfi", "Helsingin Sanomat", "hs.fi", 0.70),
    ("rte", "RTE", "rte.ie", 0.72),
    ("irishtimes", "Irish Times", "irishtimes.com", 0.74),
    ("independent_uk", "Independent", "independent.co.uk", 0.70),
    ("telegraph_uk", "Telegraph", "telegraph.co.uk", 0.74),
    ("thetimes", "The Times", "thetimes.co.uk", 0.80),
    ("guardianuk", "The Guardian", "theguardian.com", 0.78),
    ("skynews", "Sky News", "news.sky.com", 0.74),
    ("cityam", "City AM", "cityam.com", 0.68),
    ("aljazeeracom", "Al Jazeera", "aljazeera.com", 0.80),
    ("arabnews", "Arab News", "arabnews.com", 0.70),
    ("gulfnews", "Gulf News", "gulfnews.com", 0.66),
    ("thenational", "The National", "thenationalnews.com", 0.72),
    ("haaretz", "Haaretz", "haaretz.com", 0.74),
    ("timesofisrael", "Times of Israel", "timesofisrael.com", 0.72),
    ("jpost", "Jerusalem Post", "jpost.com", 0.68),
    ("dailymaverick", "Daily Maverick", "dailymaverick.co.za", 0.70),
    ("businessdayza", "Business Day", "businesslive.co.za", 0.68),
    ("reutersafrica", "Reuters Africa", "reuters.com", 0.88),
    ("valor", "Valor", "valor.globo.com", 0.72),
    ("folha", "Folha", "folha.uol.com.br", 0.68),
    ("reforma", "Reforma", "reforma.com", 0.64),
    ("lanacion", "La Nacion", "lanacion.com.ar", 0.66),
    ("eluniverso", "El Universo", "eluniverso.com", 0.58),
    ("bnamericas", "BNamericas", "bnamericas.com", 0.66),
    ("prnewswirecom", "PR Newswire", "prnewswire.com", 0.64),
    ("businesswire", "Business Wire", "businesswire.com", 0.66),
    ("globenewswire", "GlobeNewswire", "globenewswire.com", 0.64),
    ("accesswire", "AccessWire", "accesswire.com", 0.55),
    ("secfilings", "SEC Filings news", "sec.gov", 0.90),
    ("nasdaqcom", "Nasdaq", "nasdaq.com", 0.76),
    ("nyse", "NYSE", "nyse.com", 0.74),
    ("lse", "LSE", "londonstockexchange.com", 0.74),
    ("hkex", "HKEX", "hkex.com.hk", 0.74),
    ("sgx", "SGX", "sgx.com", 0.72),
    ("asx", "ASX", "asx.com.au", 0.72),
    ("tsx", "TSX", "money.tmx.com", 0.68),
    ("nvidia", "NVIDIA news", "nvidianews.nvidia.com", 0.80),
    ("appleinsider", "AppleInsider", "appleinsider.com", 0.62),
    ("macrumors", "MacRumors", "macrumors.com", 0.62),
    ("electrek", "Electrek", "electrek.co", 0.64),
    ("insideevs", "InsideEVs", "insideevs.com", 0.60),
    ("teslarati", "Teslarati", "teslarati.com", 0.58),
    ("autonews", "Automotive News", "autonews.com", 0.70),
    ("reutersauto", "Reuters Autos", "reuters.com", 0.88),
    ("flightglobal", "FlightGlobal", "flightglobal.com", 0.70),
    ("ainonline", "AIN", "ainonline.com", 0.64),
    ("statnews", "STAT", "statnews.com", 0.76),
    ("fiercepharma", "Fierce Pharma", "fiercepharma.com", 0.70),
    ("endpoints", "Endpoints", "endpts.com", 0.70),
    ("biopharmadive", "BioPharma Dive", "biopharmadive.com", 0.70),
    ("healthcareit", "Healthcare IT", "healthcareitnews.com", 0.60),
    ("law360", "Law360", "law360.com", 0.72),
    ("scotusblog", "SCOTUSblog", "scotusblog.com", 0.78),
    ("zerohedge", "ZeroHedge", "zerohedge.com", 0.45),
    ("wolfstreet", "Wolf Street", "wolfstreet.com", 0.60),
    ("calculatedrisk", "Calculated Risk", "calculatedriskblog.com", 0.64),
    ("ftalphaville", "FT Alphaville", "ft.com", 0.84),
    ("dealbook", "DealBook", "nytimes.com", 0.84),
    ("wsjpro", "WSJ Pro", "wsj.com", 0.88),
    ("yahoo_fin", "Yahoo Finance", "finance.yahoo.com", 0.66),
    ("investingcom", "Investing.com", "investing.com", 0.62),
    ("tradingview", "TradingView", "tradingview.com", 0.58),
    ("forexlive", "ForexLive", "forexlive.com", 0.64),
    ("dailyfxcom", "DailyFX", "dailyfx.com", 0.70),
    ("fxstreetcom", "FXStreet", "fxstreet.com", 0.70),
    ("babypips", "BabyPips", "babypips.com", 0.52),
    ("actionforex", "ActionForex", "actionforex.com", 0.52),
    ("metalbulletin", "Fastmarkets MB", "metalbulletin.com", 0.68),
    ("hellenicshipping", "Hellenic Shipping", "hellenicshippingnews.com", 0.58),
    ("lloydslist", "Lloyd's List", "lloydslist.com", 0.70),
    ("joc", "JOC", "joc.com", 0.68),
    ("freightwaves", "FreightWaves", "freightwaves.com", 0.64),
    ("supplychaindive", "Supply Chain Dive", "supplychaindive.com", 0.62),
    ("retail_dive", "Retail Dive", "retaildive.com", 0.60),
    ("restaurantdive", "Restaurant Dive", "restaurantdive.com", 0.55),
    ("utilitydive", "Utility Dive", "utilitydive.com", 0.64),
    ("constructiondive", "Construction Dive", "constructiondive.com", 0.58),
    ("bankingdive", "Banking Dive", "bankingdive.com", 0.64),
    ("cybersecuritydive", "Cybersecurity Dive", "cybersecuritydive.com", 0.62),
    ("krebsonsecurity", "Krebs on Security", "krebsonsecurity.com", 0.76),
    ("bleepingcomputer", "BleepingComputer", "bleepingcomputer.com", 0.64),
    ("therecord", "The Record", "therecord.media", 0.68),
    ("securityweek", "SecurityWeek", "securityweek.com", 0.64),
    ("darkreading", "Dark Reading", "darkreading.com", 0.64),
    ("spacenews", "SpaceNews", "spacenews.com", 0.70),
    ("teslarati2", "Teslarati", "teslarati.com", 0.56),
    ("payloadspace", "Payload", "payloadspace.com", 0.64),
    ("defensenews", "Defense News", "defensenews.com", 0.72),
    ("janes", "Janes", "janes.com", 0.74),
    ("breakingdefense", "Breaking Defense", "breakingdefense.com", 0.70),
    ("aviationweek", "Aviation Week", "aviationweek.com", 0.72),
    ("rigzone2", "Rigzone", "rigzone.com", 0.62),
    ("naturalgasintel", "NGI", "naturalgasintel.com", 0.66),
    ("rystad", "Rystad", "rystadenergy.com", 0.70),
    ("woodmac", "WoodMac", "woodmac.com", 0.72),
    ("bnef", "BNEF", "about.bnef.com", 0.76),
    ("pv_magazine", "pv magazine", "pv-magazine.com", 0.64),
    ("renews", "reNEWS", "renews.biz", 0.60),
    ("hydrogeninsight", "Hydrogen Insight", "hydrogeninsight.com", 0.60),
    ("miningweekly", "Mining Weekly", "miningweekly.com", 0.62),
    ("northernminer", "Northern Miner", "northernminer.com", 0.62),
    ("kitco2", "Kitco News", "kitco.com", 0.72),
    ("sharpspixley", "Sharps Pixley", "sharpspixley.com", 0.58),
    ("bullionvault", "BullionVault", "bullionvault.com", 0.58),
    ("goldseek", "GoldSeek", "goldseek.com", 0.52),
    ("oilprice2", "OilPrice", "oilprice.com", 0.76),
    ("hellenic2", "Shipping", "hellenicshippingnews.com", 0.56),
    ("gcaptain", "gCaptain", "gcaptain.com", 0.60),
    ("tradewinds", "TradeWinds", "tradewindsnews.com", 0.66),
    ("spglobal2", "S&P Global", "spglobal.com", 0.84),
    ("moodys2", "Moody's", "moodys.com", 0.80),
    ("dbrs", "Morningstar DBRS", "dbrs.morningstar.com", 0.70),
    ("pitchbook", "PitchBook", "pitchbook.com", 0.70),
    ("crunchbase", "Crunchbase", "news.crunchbase.com", 0.64),
    ("techinasia", "Tech in Asia", "techinasia.com", 0.62),
    ("restofworld", "Rest of World", "restofworld.org", 0.68),
    ("restofworld2", "Rest of World", "restofworld.org", 0.66),
    ("restofworld3", "Rest of World", "restofworld.org", 0.66),
    ("semafor2", "Semafor", "semafor.com", 0.74),
    ("puck", "Puck", "puck.news", 0.68),
    ("theblockbeats", "BlockBeats", "theblockbeats.info", 0.52),
    ("odaily", "Odaily", "odaily.news", 0.50),
    ("panewslab", "PANews", "panewslab.com", 0.52),
    ("forklog", "ForkLog", "forklog.com", 0.50),
    ("bitcoinmagazinecom", "Bitcoin Magazine", "bitcoinmagazine.com", 0.68),
    ("unchained", "Unchained", "unchainedcrypto.com", 0.64),
    ("protos", "Protos", "protos.com", 0.62),
    ("theblockpro", "The Block Pro", "theblock.co", 0.76),
    ("coindesk_markets", "CoinDesk Markets", "coindesk.com", 0.76),
    ("coindesk_policy", "CoinDesk Policy", "coindesk.com", 0.76),
    ("wsj_markets2", "WSJ Markets", "wsj.com", 0.88),
    ("bloomberg_markets2", "Bloomberg Markets", "bloomberg.com", 0.90),
    ("reuters_markets", "Reuters Markets", "reuters.com", 0.90),
    ("reuters_energy", "Reuters Energy", "reuters.com", 0.90),
    ("reuters_tech", "Reuters Tech", "reuters.com", 0.88),
    ("ap_business", "AP Business", "apnews.com", 0.86),
    ("bbc_business2", "BBC Business", "bbc.com", 0.84),
    ("bbc_world2", "BBC World", "bbc.com", 0.84),
    ("nikkei2", "Nikkei Asia", "asia.nikkei.com", 0.86),
    ("scmp2", "SCMP", "scmp.com", 0.80),
    ("ft2", "FT", "ft.com", 0.90),
    ("economist2", "Economist", "economist.com", 0.86),
    ("handelsblatt2", "Handelsblatt", "handelsblatt.com", 0.84),
    ("lesechos2", "Les Echos", "lesechos.fr", 0.80),
    ("ilsole2", "Il Sole 24 Ore", "ilsole24ore.com", 0.82),
    ("afr2", "AFR", "afr.com", 0.82),
    ("livemint2", "Mint", "livemint.com", 0.74),
    ("caixin2", "Caixin", "caixinglobal.com", 0.80),
    ("channelnewsasia2", "CNA", "channelnewsasia.com", 0.78),
    ("aljazeera2", "Al Jazeera", "aljazeera.com", 0.80),
    ("dwcom", "DW", "dw.com", 0.80),
]

# extra query-shaped google news (markets the bot actually trades)
QUERIES: List[tuple] = [
    ("q_fomc", "FOMC / Fed", "FOMC OR \"federal reserve\" OR \"rate decision\" OR Powell", 0.88),
    ("q_cpi", "US CPI", "CPI OR \"consumer price index\" OR inflation payrolls OR NFP OR PCE", 0.86),
    ("q_opec", "OPEC oil", "OPEC OR \"production cut\" OR \"crude oil\" OR WTI OR Brent", 0.84),
    ("q_gold", "Gold", "gold OR XAU OR bullion OR \"gold price\"", 0.78),
    ("q_copper", "Copper", "copper OR \"copper price\" OR XCU", 0.76),
    ("q_natgas", "Nat gas", "\"natural gas\" OR Henry Hub OR LNG", 0.74),
    ("q_wheat", "Wheat / grains", "wheat OR corn OR soybean OR USDA", 0.70),
    ("q_btc", "Bitcoin", "Bitcoin OR BTC OR \"spot bitcoin ETF\"", 0.80),
    ("q_eth", "Ethereum", "Ethereum OR ETH OR \"ether ETF\"", 0.80),
    ("q_sol", "Solana", "Solana OR SOL", 0.70),
    ("q_hype", "Hyperliquid", "Hyperliquid OR HYPE", 0.72),
    ("q_sec", "SEC crypto", "SEC (crypto OR bitcoin OR ethereum OR ETF OR listing)", 0.88),
    ("q_etf", "ETF flows", "ETF (bitcoin OR ethereum OR gold OR inflows)", 0.76),
    ("q_nvda", "NVIDIA", "NVIDIA OR NVDA OR Jensen Huang", 0.80),
    ("q_aapl", "Apple", "Apple OR AAPL (earnings OR listing OR guidance)", 0.78),
    ("q_tsla", "Tesla", "Tesla OR TSLA OR Musk", 0.74),
    ("q_msft", "Microsoft", "Microsoft OR MSFT", 0.78),
    ("q_amzn", "Amazon", "Amazon OR AMZN", 0.76),
    ("q_googl", "Alphabet", "Alphabet OR Google OR GOOGL", 0.76),
    ("q_meta", "Meta", "Meta OR Facebook OR META", 0.74),
    ("q_avgo", "Broadcom", "Broadcom OR AVGO", 0.74),
    ("q_amd", "AMD", "AMD OR \"Advanced Micro Devices\"", 0.72),
    ("q_intc", "Intel", "Intel OR INTC", 0.70),
    ("q_tsm", "TSMC", "TSMC OR \"Taiwan Semiconductor\"", 0.78),
    ("q_asml", "ASML", "ASML", 0.76),
    ("q_pltr", "Palantir", "Palantir OR PLTR", 0.68),
    ("q_coin", "Coinbase stock", "Coinbase OR COIN", 0.74),
    ("q_mstr", "MicroStrategy", "MicroStrategy OR MSTR OR Strategy", 0.70),
    ("q_spy", "S&P 500", "S&P 500 OR SPX OR SPY", 0.78),
    ("q_qqq", "Nasdaq 100", "Nasdaq-100 OR QQQ OR \"tech stocks\"", 0.76),
    ("q_dxy", "US dollar", "DXY OR \"dollar index\" OR \"US dollar\"", 0.76),
    ("q_eurusd", "EURUSD", "EURUSD OR euro dollar ECB", 0.74),
    ("q_usdjpy", "USDJPY", "USDJPY OR yen BOJ", 0.76),
    ("q_gbpusd", "GBPUSD", "GBPUSD OR sterling OR \"Bank of England\"", 0.72),
    ("q_china", "China markets", "China (stocks OR yuan OR PBOC OR property OR stimulus)", 0.78),
    ("q_war", "Geopolitics energy", "(Iran OR Strait of Hormuz OR Ukraine) (oil OR sanctions)", 0.80),
    ("q_sanctions", "Sanctions", "sanctions OR tariff OR embargo (oil OR china OR iran)", 0.80),
    ("q_banks", "Banks", "JPMorgan OR Goldman OR \"Credit Suisse\" OR SVB OR \"bank failure\"", 0.76),
    ("q_hack", "Crypto exploit", "hack OR exploit OR drained (bridge OR protocol OR exchange)", 0.86),
    ("q_listing", "Exchange listing", "(Binance OR Coinbase OR Kraken) (list OR listing OR delist)", 0.82),
    ("q_zklighter", "zkLighter", "zkLighter OR \"Lighter DEX\" OR \"Lighter protocol\"", 0.74),
    ("q_rwa", "RWA token", "RWA OR \"real world asset\" tokenization", 0.70),
    ("q_stablecoin", "Stablecoin", "USDC OR USDT OR stablecoin (depeg OR mint OR circle)", 0.76),
    ("q_ppi", "US PPI", "PPI OR \"producer price index\" OR \"jobless claims\"", 0.82),
    ("q_boj", "BOJ yen", "BOJ OR \"Bank of Japan\" OR \"yen intervention\"", 0.80),
    ("q_pboc", "PBOC", "PBOC OR \"People's Bank of China\" OR yuan", 0.78),
    ("q_unlock", "Token unlock", "\"token unlock\" OR \"cliff unlock\"", 0.70),
    ("q_earnings", "Mega-cap earnings", "earnings (Apple OR Microsoft OR NVIDIA OR Tesla OR Amazon)", 0.78),
    ("q_ai", "AI chips", "AI (NVIDIA OR TSMC OR \"data center\" OR GPU)", 0.74),
    ("q_rates", "Rates", "\"Treasury yield\" OR \"10-year\" OR \"rate cut\" OR hawkish OR dovish", 0.80),
    ("q_ecb", "ECB", "ECB OR Lagarde OR \"deposit rate\" euro", 0.82),
    ("q_rba", "RBA", "RBA OR \"Reserve Bank of Australia\"", 0.76),
    ("q_boc", "Bank of Canada", "\"Bank of Canada\" OR BoC OR loonie", 0.74),
    ("q_snb", "SNB", "SNB OR \"Swiss National Bank\" franc", 0.74),
    ("q_tariff", "Tariffs", "tariff OR \"trade war\" OR \"section 301\" China", 0.80),
    ("q_shutdown", "US shutdown", "\"government shutdown\" OR \"debt ceiling\"", 0.78),
    ("q_payrolls", "Payrolls", "\"nonfarm payrolls\" OR NFP OR \"jobless claims\"", 0.84),
    ("q_ism", "ISM PMI", "ISM OR PMI OR \"manufacturing PMI\"", 0.76),
    ("q_housing", "US housing", "\"existing home sales\" OR \"housing starts\" OR NAHB", 0.70),
    ("q_retail", "Retail sales", "\"retail sales\" OR \"consumer spending\"", 0.72),
    ("q_gdp", "GDP", "GDP OR \"gross domestic product\" recession", 0.74),
    ("q_btc_etf", "Bitcoin ETF", "\"bitcoin ETF\" OR IBIT OR FBTC OR GBTC", 0.80),
    ("q_eth_etf", "Ether ETF", "\"ether ETF\" OR ETHA OR FETH", 0.78),
    ("q_stable_depeg", "Depeg", "depeg OR \"broke the buck\" USDC USDT", 0.82),
    ("q_bridge", "Bridge hack", "\"bridge hack\" OR \"cross-chain\" exploit drained", 0.84),
    ("q_sec_binance", "SEC Binance", "SEC (Binance OR Coinbase OR Ripple OR Kraken)", 0.84),
    ("q_clarity", "US crypto bill", "\"Clarity Act\" OR CLARITY OR FIT21 OR SAB 121", 0.76),
    ("q_genius", "GENIUS Act", "GENIUS Act OR \"stablecoin bill\"", 0.74),
    ("q_ai_capex", "AI capex", "\"AI capex\" OR \"data center\" OR GPU cluster", 0.76),
    ("q_tsmc_quake", "TSMC risk", "TSMC (earthquake OR drought OR Arizona OR CoWoS)", 0.78),
    ("q_hormuz", "Hormuz oil", "\"Strait of Hormuz\" OR Hormuz tanker oil", 0.84),
    ("q_russia_oil", "Russia oil", "\"Russian oil\" OR \"price cap\" Urals diesel", 0.78),
    ("q_opec_plus", "OPEC+", "\"OPEC+\" OR \"voluntary cut\" or spare capacity", 0.80),
    ("q_gold_etf", "Gold ETF", "GLD OR IAU OR \"gold ETF\" inflows", 0.72),
    ("q_copper_mine", "Copper mine", "copper (strike OR mine OR Codelco OR Escondida)", 0.76),
    ("q_lng", "LNG", "LNG OR \"liquefied natural gas\" OR Cheniere", 0.74),
    ("q_refinery", "Refinery", "refinery (outage OR explosion OR crack spread)", 0.74),
    ("q_bank_stress", "Bank stress", "\"bank failure\" OR AT1 OR \"regional bank\" OR CRE", 0.80),
    ("q_yen_int", "Yen intervention", "\"yen intervention\" OR \"currency intervention\" BOJ", 0.82),
]

# Lighter-style tickers → Google News queries (equities, crypto, FX, commodities, RWAs)
TICKERS: List[tuple] = [
    ("AAPL", "Apple AAPL"), ("MSFT", "Microsoft MSFT"), ("AMZN", "Amazon AMZN"),
    ("NVDA", "NVIDIA NVDA"), ("GOOGL", "Alphabet Google GOOGL"), ("META", "Meta META"),
    ("TSLA", "Tesla TSLA"), ("AVGO", "Broadcom AVGO"), ("AMD", "AMD"), ("INTC", "Intel INTC"),
    ("ORCL", "Oracle ORCL"), ("PLTR", "Palantir PLTR"), ("CRM", "Salesforce CRM"),
    ("ADBE", "Adobe ADBE"), ("NFLX", "Netflix NFLX"), ("DIS", "Disney DIS"),
    ("QCOM", "Qualcomm QCOM"), ("MU", "Micron MU"), ("ARM", "ARM Holdings"),
    ("TSM", "TSMC"), ("ASML", "ASML"), ("AMAT", "Applied Materials AMAT"),
    ("LRCX", "Lam Research LRCX"), ("KLAC", "KLA KLAC"), ("SNPS", "Synopsys SNPS"),
    ("CDNS", "Cadence CDNS"), ("NOW", "ServiceNow NOW"), ("SNOW", "Snowflake SNOW"),
    ("DDOG", "Datadog DDOG"), ("NET", "Cloudflare NET"), ("CRWD", "CrowdStrike CRWD"),
    ("PANW", "Palo Alto PANW"), ("ZS", "Zscaler ZS"), ("OKTA", "Okta OKTA"),
    ("SMCI", "Super Micro SMCI"), ("DELL", "Dell DELL"), ("HPQ", "HP HPQ"),
    ("IBM", "IBM"), ("CSCO", "Cisco CSCO"), ("AVGO2", "Broadcom"),
    ("COIN", "Coinbase COIN"), ("HOOD", "Robinhood HOOD"), ("MSTR", "MicroStrategy MSTR"),
    ("SQ", "Block Square SQ"), ("PYPL", "PayPal PYPL"), ("V", "Visa V"),
    ("MA", "Mastercard MA"), ("JPM", "JPMorgan JPM"), ("GS", "Goldman Sachs GS"),
    ("MS", "Morgan Stanley MS"), ("BAC", "Bank of America BAC"), ("WFC", "Wells Fargo WFC"),
    ("C", "Citigroup C"), ("BRK", "Berkshire Hathaway"), ("UNH", "UnitedHealth UNH"),
    ("JNJ", "Johnson Johnson JNJ"), ("PFE", "Pfizer PFE"), ("MRNA", "Moderna MRNA"),
    ("LLY", "Eli Lilly LLY"), ("ABBV", "AbbVie ABBV"), ("MRK", "Merck MRK"),
    ("XOM", "Exxon XOM"), ("CVX", "Chevron CVX"), ("COP", "ConocoPhillips COP"),
    ("SLB", "Schlumberger SLB"), ("OXY", "Occidental OXY"), ("BP", "BP oil"),
    ("SHEL", "Shell SHEL"), ("TTE", "TotalEnergies"), ("BA", "Boeing BA"),
    ("GE", "GE Aerospace"), ("CAT", "Caterpillar CAT"), ("DE", "John Deere DE"),
    ("HON", "Honeywell HON"), ("UPS", "UPS"), ("FDX", "FedEx FDX"),
    ("UBER", "Uber UBER"), ("ABNB", "Airbnb ABNB"), ("DAL", "Delta DAL"),
    ("UAL", "United Airlines UAL"), ("AAL", "American Airlines AAL"),
    ("NKE", "Nike NKE"), ("SBUX", "Starbucks SBUX"), ("MCD", "McDonalds MCD"),
    ("WMT", "Walmart WMT"), ("COST", "Costco COST"), ("TGT", "Target TGT"),
    ("HD", "Home Depot HD"), ("LOW", "Lowe's LOW"), ("PG", "Procter Gamble PG"),
    ("KO", "Coca-Cola KO"), ("PEP", "Pepsi PEP"), ("NFLX2", "Netflix"),
    ("RIVN", "Rivian RIVN"), ("LCID", "Lucid LCID"), ("NIO", "NIO stock"),
    ("XPEV", "XPeng XPEV"), ("LI", "Li Auto"), ("F", "Ford F"), ("GM", "GM stock"),
    ("TM", "Toyota TM"), ("HMC", "Honda HMC"), ("HYUNDAIUSD", "Hyundai"),
    ("BABA", "Alibaba BABA"), ("JD", "JD.com JD"), ("PDD", "PDD Pinduoduo"),
    ("BIDU", "Baidu BIDU"), ("TCEHY", "Tencent"), ("TENCENT", "Tencent"),
    ("XIAOMI", "Xiaomi"), ("BYD", "BYD stock"), ("NIO2", "NIO"),
    ("SAMSUNGUSD", "Samsung"), ("SONY", "Sony SONY"), ("NOK", "Nokia NOK"),
    ("SHOP", "Shopify SHOP"), ("SE", "Sea Limited SE"), ("MELI", "MercadoLibre MELI"),
    ("NU", "Nu Holdings NU"), ("GRAB", "Grab GRAB"), ("CPNG", "Coupang CPNG"),
    ("GME", "GameStop GME"), ("AMC", "AMC stock"), ("BB", "BlackBerry BB"),
    ("SPY", "S&P 500 SPY"), ("QQQ", "Nasdaq 100 QQQ"), ("IWM", "Russell 2000 IWM"),
    ("DIA", "Dow DIA"), ("VIX", "VIX volatility"), ("US10Y", "US 10-year Treasury yield"),
    ("TLT", "TLT bonds"), ("HYG", "high yield HYG"), ("GLD", "GLD gold ETF"),
    ("SLV", "SLV silver ETF"), ("USO", "USO oil ETF"), ("UNG", "UNG gas ETF"),
    ("BTC", "Bitcoin BTC"), ("ETH", "Ethereum ETH"), ("SOL", "Solana SOL"),
    ("HYPE", "Hyperliquid HYPE"), ("XRP", "XRP Ripple"), ("DOGE", "Dogecoin DOGE"),
    ("ADA", "Cardano ADA"), ("AVAX", "Avalanche AVAX"), ("BNB", "BNB Binance"),
    ("LTC", "Litecoin LTC"), ("LINK", "Chainlink LINK"), ("DOT", "Polkadot DOT"),
    ("SUI", "Sui SUI"), ("APT", "Aptos APT"), ("TON", "Toncoin TON"),
    ("NEAR", "NEAR protocol"), ("FIL", "Filecoin FIL"), ("ATOM", "Cosmos ATOM"),
    ("UNI", "Uniswap UNI"), ("AAVE", "Aave AAVE"), ("MKR", "Maker MKR"),
    ("PEPE", "PEPE coin"), ("WIF", "dogwifhat WIF"), ("BONK", "BONK coin"),
    ("SHIB", "Shiba SHIB"), ("TRX", "TRON TRX"), ("BCH", "Bitcoin Cash BCH"),
    ("ETC", "Ethereum Classic ETC"), ("XLM", "Stellar XLM"), ("HBAR", "Hedera HBAR"),
    ("ARB", "Arbitrum ARB"), ("OP", "Optimism OP"), ("MATIC", "Polygon MATIC"),
    ("RENDER", "Render RENDER"), ("FET", "Fetch.ai FET"), ("TAO", "Bittensor TAO"),
    ("WLD", "Worldcoin WLD"), ("ONDO", "Ondo ONDO"), ("JUP", "Jupiter JUP"),
    ("EURUSD", "EURUSD euro"), ("GBPUSD", "GBPUSD sterling"), ("USDJPY", "USDJPY yen"),
    ("AUDUSD", "AUDUSD Aussie"), ("NZDUSD", "NZDUSD kiwi"), ("USDCAD", "USDCAD loonie"),
    ("USDCHF", "USDCHF franc"), ("USDHKD", "USDHKD"), ("USDKRW", "USDKRW won"),
    ("EURJPY", "EURJPY"), ("GBPJPY", "GBPJPY"), ("EURGBP", "EURGBP"),
    ("XAU", "gold XAU"), ("XAG", "silver XAG"), ("XCU", "copper XCU"),
    ("XAUT", "Tether Gold XAUT"), ("XPT", "platinum XPT"), ("XPD", "palladium XPD"), ("PAXG", "PAXG gold"),
    ("WTI", "WTI crude oil"), ("BRENTOIL", "Brent crude"), ("NATGAS", "natural gas LNG"),
    ("WHEAT", "wheat grain USDA"), ("CORN", "corn grain"), ("SOY", "soybean"),
    ("OPENAI", "OpenAI"), ("ANTHROPIC", "Anthropic"), ("SPCX", "SpaceX"),
    ("HOOD2", "Robinhood"), ("CRCL", "Circle CRCL"), ("USDC", "USDC Circle"),
    ("USDT", "Tether USDT"), ("MSTR2", "Strategy MSTR bitcoin"),
    ("BLK", "BlackRock BLK"), ("BX", "Blackstone BX"), ("KKR", "KKR"),
    ("APO", "Apollo APO"), ("ARKK", "ARKK Cathie Wood"), ("QQQ2", "Invesco QQQ"),
    ("NVDA2", "NVIDIA chips AI"), ("TSMC2", "TSMC Arizona"), ("ASML2", "ASML EUV"),
    ("RBLX", "Roblox RBLX"), ("U", "Unity U"), ("EA", "Electronic Arts EA"),
    ("TTWO", "Take-Two TTWO"), ("SONY2", "Sony PlayStation"),
    ("BA2", "Boeing 737 MAX"), ("LMT", "Lockheed LMT"), ("RTX", "RTX Raytheon"),
    ("NOC", "Northrop NOC"), ("GD", "General Dynamics GD"),
    ("PLD", "Prologis PLD"), ("AMT", "American Tower AMT"), ("CCI", "Crown Castle CCI"),
    ("EQIX", "Equinix EQIX"), ("DLR", "Digital Realty DLR"),
    ("NEE", "NextEra NEE"), ("DUK", "Duke Energy DUK"), ("SO", "Southern Company SO"),
    ("LIN", "Linde LIN"), ("APD", "Air Products APD"), ("SHW", "Sherwin Williams SHW"),
    ("FCX", "Freeport FCX"), ("NEM", "Newmont NEM"), ("GOLD", "Barrick GOLD"),
    ("VALE", "Vale VALE"), ("BHP", "BHP"), ("RIO", "Rio Tinto RIO"),
    ("SCCO", "Southern Copper SCCO"), ("AA", "Alcoa AA"), ("X", "US Steel X"),
    ("CL", "Colgate CL"), ("EL", "Estee Lauder EL"), ("LVMUY", "LVMH"),
    ("NVO", "Novo Nordisk NVO"), ("AZN", "AstraZeneca AZN"), ("RHHBY", "Roche"),
    ("SNY", "Sanofi SNY"), ("GSK", "GSK"),
    ("ABT", "Abbott ABT"), ("TMO", "Thermo Fisher TMO"), ("DHR", "Danaher DHR"),
    ("ISRG", "Intuitive Surgical ISRG"), ("SYK", "Stryker SYK"), ("BSX", "Boston Scientific BSX"),
    ("MDT", "Medtronic MDT"), ("ELV", "Elevance ELV"), ("CI", "Cigna CI"),
    ("HUM", "Humana HUM"), ("CVS", "CVS Health"), ("AMGN", "Amgen AMGN"),
    ("GILD", "Gilead GILD"), ("BMY", "Bristol Myers BMY"), ("REGN", "Regeneron REGN"),
    ("VRTX", "Vertex VRTX"), ("BIIB", "Biogen BIIB"), ("DXCM", "Dexcom DXCM"),
    ("TXN", "Texas Instruments TXN"), ("ADI", "Analog Devices ADI"), ("NXPI", "NXP NXPI"),
    ("MCHP", "Microchip MCHP"), ("ON", "ON Semiconductor"), ("MPWR", "Monolithic Power"),
    ("INTU", "Intuit INTU"), ("WDAY", "Workday WDAY"), ("TEAM", "Atlassian TEAM"),
    ("FTNT", "Fortinet FTNT"), ("HUBS", "HubSpot HUBS"), ("MDB", "MongoDB MDB"),
    ("ESTC", "Elastic ESTC"), ("GTLB", "GitLab GTLB"), ("PATH", "UiPath PATH"),
    ("BKNG", "Booking BKNG"), ("MAR", "Marriott MAR"), ("HLT", "Hilton HLT"),
    ("RCL", "Royal Caribbean RCL"), ("CCL", "Carnival CCL"), ("CMG", "Chipotle CMG"),
    ("YUM", "Yum YUM"), ("LULU", "Lululemon LULU"), ("TJX", "TJX"),
    ("CME", "CME Group"), ("ICE", "Intercontinental Exchange ICE"), ("SPGI", "S&P Global SPGI"),
    ("MCO", "Moody's MCO"), ("NDAQ", "Nasdaq NDAQ"), ("SCHW", "Charles Schwab SCHW"),
    ("TROW", "T Rowe Price"), ("AIG", "AIG"), ("MET", "MetLife MET"),
    ("PGR", "Progressive PGR"), ("TRV", "Travelers TRV"), ("CB", "Chubb CB"),
    ("SPG", "Simon SPG"), ("O", "Realty Income O"), ("WELL", "Welltower WELL"),
    ("AEP", "American Electric AEP"), ("SRE", "Sempra SRE"), ("D", "Dominion D"),
    ("WM", "Waste Management WM"), ("RSG", "Republic Services RSG"),
    ("MMM", "3M MMM"), ("ITW", "Illinois Tool ITW"), ("EMR", "Emerson EMR"),
    ("ETN", "Eaton ETN"), ("PH", "Parker PH"), ("CARR", "Carrier CARR"),
    ("UNP", "Union Pacific UNP"), ("CSX", "CSX"), ("NSC", "Norfolk Southern NSC"),
    ("PM", "Philip Morris PM"), ("MO", "Altria MO"), ("T", "AT&T T"),
    ("VZ", "Verizon VZ"), ("TMUS", "T-Mobile TMUS"), ("CMCSA", "Comcast CMCSA"),
    ("CHTR", "Charter CHTR"), ("SPOT", "Spotify SPOT"), ("SNAP", "Snap SNAP"),
    ("PINS", "Pinterest PINS"), ("RDDT", "Reddit RDDT"), ("U2", "Unity Software"),
    ("RBLX", "Roblox RBLX"), ("EA", "Electronic Arts EA"), ("TTWO", "Take-Two TTWO"),
    ("MARA", "MARA Holdings"), ("RIOT", "Riot Platforms RIOT"), ("CLSK", "CleanSpark CLSK"),
    ("IREN", "IREN bitcoin miner"), ("CIFR", "Cipher Mining CIFR"), ("HUT", "Hut 8 HUT"),
    ("SOFI", "SoFi SOFI"), ("AFRM", "Affirm AFRM"), ("UPST", "Upstart UPST"),
    ("RKLB", "Rocket Lab RKLB"), ("ASTS", "AST SpaceMobile ASTS"),
    ("INJ", "Injective INJ"), ("TIA", "Celestia TIA"), ("SEI", "Sei SEI"),
    ("STX", "Stacks STX"), ("IMX", "Immutable IMX"), ("GRT", "The Graph GRT"),
    ("LDO", "Lido LDO"), ("PENDLE", "Pendle PENDLE"), ("ENA", "Ethena ENA"),
    ("JUP", "Jupiter JUP"), ("PYTH", "Pyth PYTH"), ("W", "Wormhole W"),
    ("SAND", "The Sandbox SAND"), ("MANA", "Decentraland MANA"), ("AXS", "Axie AXS"),
    ("SHIB2", "Shiba Inu"), ("PEPE2", "PEPE memecoin"), ("WIF2", "dogwifhat"),
    ("EURCHF", "EURCHF"), ("AUDJPY", "AUDJPY"), ("EURAUD", "EURAUD"),
    ("GBPAUD", "GBPAUD"), ("USDCNH", "USDCNH yuan"), ("USDMXN", "USDMXN peso"),
    ("USDZAR", "USDZAR rand"), ("USDTRY", "USDTRY lira"), ("USDINR", "USDINR rupee"),
    ("USDSGD", "USDSGD"), ("USDTWD", "USDTWD"), ("EURGBP", "EURGBP"),
    ("NICKEL", "nickel price LME"), ("ZINC", "zinc price"), ("ALUMINUM", "aluminum LME"),
    ("IRON", "iron ore price"), ("LITHIUM", "lithium price"), ("URANIUM", "uranium SPUT"),
    ("COFFEE", "coffee futures"), ("SUGAR", "sugar futures"), ("COTTON", "cotton futures"),
    ("HSI", "Hang Seng HSI"), ("NKY", "Nikkei 225"), ("DAX", "DAX index"),
    ("CAC", "CAC 40"), ("FTSE", "FTSE 100"), ("KOSPI", "KOSPI"),
    ("ASX200", "ASX 200"), ("STOXX", "Euro Stoxx 50"),
    ("MCD2", "McDonalds"), ("SBUX2", "Starbucks"), ("NKE2", "Nike"),
    ("HD2", "Home Depot"), ("LOW2", "Lowes"), ("TGT2", "Target"),
    ("COST2", "Costco"), ("WMT2", "Walmart"), ("PG2", "P&G"),
    ("KO2", "Coca-Cola"), ("PEP2", "Pepsi"),
    ("LLY2", "Eli Lilly GLP-1"), ("NVO2", "Novo Nordisk Ozempic"),
    ("UNH2", "UnitedHealth"), ("ISRG2", "Intuitive da Vinci"),
    ("CRWD2", "CrowdStrike outage"), ("PANW2", "Palo Alto Networks"),
    ("SNOW2", "Snowflake"), ("PLTR2", "Palantir AIP"),
    ("UBER2", "Uber"), ("ABNB2", "Airbnb"), ("DASH", "DoorDash DASH"),
    ("CART", "Instacart CART"), ("CELH", "Celsius CELH"), ("MNST", "Monster MNST"),
    ("DKNG", "DraftKings DKNG"), ("PENN", "Penn Entertainment"),
    ("WYNN", "Wynn WYNN"), ("MGM", "MGM Resorts"), ("LVS", "Las Vegas Sands LVS"),
    ("RIVN2", "Rivian"), ("LCID2", "Lucid Motors"), ("F2", "Ford EV"),
    ("GM2", "GM Ultium"), ("TSLA2", "Tesla robotaxi"),
    ("BABA2", "Alibaba"), ("PDD2", "PDD Temu"), ("JD2", "JD.com"),
    ("TSM2", "TSMC CoWoS"), ("ASML2B", "ASML High-NA"),
    ("XOM2", "Exxon Guyana"), ("CVX2", "Chevron"), ("SLB2", "SLB"),
    ("NEM2", "Newmont gold"), ("FCX2", "Freeport copper"), ("SCCO2", "Southern Copper"),
    ("VALE2", "Vale iron"), ("BHP2", "BHP"), ("RIO2", "Rio Tinto"),
    ("CCJ", "Cameco CCJ uranium"), ("UEC", "Uranium Energy UEC"),
    ("ALB", "Albemarle ALB lithium"), ("SQM", "SQM lithium"),
    ("MP", "MP Materials rare earth"), ("LYC", "Lynas rare earth"),
]

LOCALES = [
    ("us", "en-US", "US", "US:en"),
    ("gb", "en-GB", "GB", "GB:en"),
    ("in", "en-IN", "IN", "IN:en"),
    ("au", "en-AU", "AU", "AU:en"),
    ("ca", "en-CA", "CA", "CA:en"),
    ("sg", "en-SG", "SG", "SG:en"),
    ("hk", "en-HK", "HK", "HK:en"),
    ("ae", "en-AE", "AE", "AE:en"),
    ("za", "en-ZA", "ZA", "ZA:en"),
    ("ie", "en-IE", "IE", "IE:en"),
    ("nz", "en-NZ", "NZ", "NZ:en"),
    ("ph", "en-PH", "PH", "PH:en"),
    ("de", "en-DE", "DE", "DE:en"),
    ("fr", "en-FR", "FR", "FR:en"),
    ("jp", "en-JP", "JP", "JP:en"),
    ("kr", "en-KR", "KR", "KR:en"),
    ("br", "en-BR", "BR", "BR:en"),
    ("mx", "en-MX", "MX", "MX:en"),
    ("ch", "en-CH", "CH", "CH:en"),
    ("nl", "en-NL", "NL", "NL:en"),
    ("se", "en-SE", "SE", "SE:en"),
    ("it", "en-IT", "IT", "IT:en"),
    ("es", "en-ES", "ES", "ES:en"),
    ("tw", "en-TW", "TW", "TW:en"),
    ("th", "en-TH", "TH", "TH:en"),
    ("id", "en-ID", "ID", "ID:en"),
    ("my", "en-MY", "MY", "MY:en"),
    ("pl", "en-PL", "PL", "PL:en"),
    ("tr", "en-TR", "TR", "TR:en"),
    ("sa", "en-SA", "SA", "SA:en"),
    ("ng", "en-NG", "NG", "NG:en"),
    ("at", "en-AT", "AT", "AT:en"),
    ("be", "en-BE", "BE", "BE:en"),
    ("dk", "en-DK", "DK", "DK:en"),
    ("fi", "en-FI", "FI", "FI:en"),
    ("pt", "en-PT", "PT", "PT:en"),
    ("cz", "en-CZ", "CZ", "CZ:en"),
    ("gr", "en-GR", "GR", "GR:en"),
    ("hu", "en-HU", "HU", "HU:en"),
    ("ro", "en-RO", "RO", "RO:en"),
    ("eg", "en-EG", "EG", "EG:en"),
    ("ke", "en-KE", "KE", "KE:en"),
    ("ar", "en-AR", "AR", "AR:en"),
    ("cl", "en-CL", "CL", "CL:en"),
    ("co", "en-CO", "CO", "CO:en"),
    ("pe", "en-PE", "PE", "PE:en"),
    ("pk", "en-PK", "PK", "PK:en"),
    ("bd", "en-BD", "BD", "BD:en"),
    ("lk", "en-LK", "LK", "LK:en"),
    ("qa", "en-QA", "QA", "QA:en"),
    ("kw", "en-KW", "KW", "KW:en"),
    ("il", "en-IL", "IL", "IL:en"),
    ("vn", "en-VN", "VN", "VN:en"),
]
TOPICS = ("BUSINESS", "TECHNOLOGY", "WORLD", "NATION", "SCIENCE", "HEALTH")

DIRECT: List[Dict] = [
    {"source_id": "cnn_top", "publisher": "CNN", "url": "http://rss.cnn.com/rss/edition.rss", "trust_score": 0.70, "interval_seconds": 40},
    {"source_id": "cnn_world", "publisher": "CNN World", "url": "http://rss.cnn.com/rss/edition_world.rss", "trust_score": 0.70, "interval_seconds": 45},
    {"source_id": "npr_news", "publisher": "NPR", "url": "https://feeds.npr.org/1001/rss.xml", "trust_score": 0.82, "interval_seconds": 40},
    {"source_id": "npr_business", "publisher": "NPR Business", "url": "https://feeds.npr.org/1006/rss.xml", "trust_score": 0.80, "interval_seconds": 45},
    {"source_id": "politico_rss", "publisher": "Politico", "url": "https://rss.politico.com/politics-news.xml", "trust_score": 0.80, "interval_seconds": 40},
    {"source_id": "thehill_rss", "publisher": "The Hill", "url": "https://thehill.com/feed/", "trust_score": 0.74, "interval_seconds": 40},
    {"source_id": "axios_rss", "publisher": "Axios", "url": "https://api.axios.com/feed/", "trust_score": 0.76, "interval_seconds": 40},
    {"source_id": "bbc_tech", "publisher": "BBC Tech", "url": "https://feeds.bbci.co.uk/news/technology/rss.xml", "trust_score": 0.82, "interval_seconds": 40},
    {"source_id": "bbc_science", "publisher": "BBC Science", "url": "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml", "trust_score": 0.80, "interval_seconds": 50},
    {"source_id": "guardian_uk", "publisher": "Guardian UK", "url": "https://www.theguardian.com/uk-news/rss", "trust_score": 0.76, "interval_seconds": 40},
    {"source_id": "guardian_tech", "publisher": "Guardian Tech", "url": "https://www.theguardian.com/uk/technology/rss", "trust_score": 0.74, "interval_seconds": 45},
    {"source_id": "nyt_tech", "publisher": "NYT Tech", "url": "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml", "trust_score": 0.84, "interval_seconds": 40},
    {"source_id": "nyt_economy", "publisher": "NYT Economy", "url": "https://rss.nytimes.com/services/xml/rss/nyt/Economy.xml", "trust_score": 0.86, "interval_seconds": 40},
    {"source_id": "nyt_energy", "publisher": "NYT Energy", "url": "https://rss.nytimes.com/services/xml/rss/nyt/EnergyEnvironment.xml", "trust_score": 0.82, "interval_seconds": 50},
    {"source_id": "wired_rss", "publisher": "Wired", "url": "https://www.wired.com/feed/rss", "trust_score": 0.72, "interval_seconds": 45},
    {"source_id": "engadget_rss", "publisher": "Engadget", "url": "https://www.engadget.com/rss.xml", "trust_score": 0.62, "interval_seconds": 45},
    {"source_id": "forbes_rss", "publisher": "Forbes", "url": "https://www.forbes.com/business/feed/", "trust_score": 0.68, "interval_seconds": 40},
    {"source_id": "bi_rss", "publisher": "Business Insider", "url": "https://www.businessinsider.com/rss", "trust_score": 0.64, "interval_seconds": 40},
    {"source_id": "sa_rss", "publisher": "Seeking Alpha", "url": "https://seekingalpha.com/market_currents.xml", "trust_score": 0.62, "interval_seconds": 30},
    {"source_id": "benzinga_rss", "publisher": "Benzinga", "url": "https://www.benzinga.com/feed", "trust_score": 0.60, "interval_seconds": 30},
    {"source_id": "independent_rss", "publisher": "Independent", "url": "https://www.independent.co.uk/news/business/rss", "trust_score": 0.70, "interval_seconds": 45},
    {"source_id": "sky_rss", "publisher": "Sky News", "url": "https://feeds.skynews.com/feeds/rss/business.xml", "trust_score": 0.74, "interval_seconds": 40},
    {"source_id": "abc_au_bus", "publisher": "ABC Australia Business", "url": "https://www.abc.net.au/news/feed/51892/rss.xml", "trust_score": 0.76, "interval_seconds": 45},
    {"source_id": "smh_rss", "publisher": "SMH", "url": "https://www.smh.com.au/rss/feed.xml", "trust_score": 0.74, "interval_seconds": 45},
    {"source_id": "afr_rss", "publisher": "AFR", "url": "https://news.google.com/rss/search?q=site:afr.com+when:12h&hl=en-US&gl=US&ceid=US:en", "trust_score": 0.80, "interval_seconds": 40},
    {"source_id": "cna_rss", "publisher": "CNA", "url": "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml", "trust_score": 0.76, "interval_seconds": 40},
    {"source_id": "scmp_rss", "publisher": "SCMP", "url": "https://www.scmp.com/rss/2/feed", "trust_score": 0.78, "interval_seconds": 40},
    {"source_id": "japantimes_rss", "publisher": "Japan Times", "url": "https://www.japantimes.co.jp/feed/", "trust_score": 0.74, "interval_seconds": 50},
    {"source_id": "koreaherald_rss", "publisher": "Korea Herald", "url": "https://news.google.com/rss/search?q=site:koreaherald.com+when:12h&hl=en-US&gl=US&ceid=US:en", "trust_score": 0.70, "interval_seconds": 50},
    {"source_id": "hindu_bus", "publisher": "The Hindu Business", "url": "https://www.thehindu.com/business/feeder/default.rss", "trust_score": 0.72, "interval_seconds": 45},
    {"source_id": "mint_rss", "publisher": "Mint", "url": "https://www.livemint.com/rss/news", "trust_score": 0.72, "interval_seconds": 40},
    {"source_id": "et_rss", "publisher": "Economic Times", "url": "https://economictimes.indiatimes.com/rssfeedstopstories.cms", "trust_score": 0.70, "interval_seconds": 40},
    {"source_id": "cbc_bus", "publisher": "CBC Business", "url": "https://www.cbc.ca/webfeed/rss/rss-business", "trust_score": 0.76, "interval_seconds": 45},
    {"source_id": "globe_rss", "publisher": "Globe and Mail", "url": "https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/business/", "trust_score": 0.78, "interval_seconds": 45},
    {"source_id": "france24_rss", "publisher": "France24", "url": "https://www.france24.com/en/rss", "trust_score": 0.76, "interval_seconds": 40},
    {"source_id": "spiegel_rss", "publisher": "Spiegel International", "url": "https://www.spiegel.de/international/index.rss", "trust_score": 0.78, "interval_seconds": 45},
    {"source_id": "elpais_rss", "publisher": "El Pais EN", "url": "https://feeds.elpais.com/mrss-s/pages/ep/site/english.elpais.com/portada", "trust_score": 0.74, "interval_seconds": 50},
    {"source_id": "aljazeera_rss2", "publisher": "Al Jazeera", "url": "https://www.aljazeera.com/xml/rss/all.xml", "trust_score": 0.80, "interval_seconds": 30},
    {"source_id": "dw_bus", "publisher": "DW Business", "url": "https://rss.dw.com/rdf/rss-en-bus", "trust_score": 0.78, "interval_seconds": 45},
    {"source_id": "whitehouse_rss", "publisher": "White House", "url": "https://news.google.com/rss/search?q=site:whitehouse.gov+when:12h&hl=en-US&gl=US&ceid=US:en", "trust_score": 0.86, "category": "official", "adapter": "official", "interval_seconds": 60},
    {"source_id": "fdic_rss", "publisher": "FDIC", "url": "https://news.google.com/rss/search?q=site:fdic.gov+when:12h&hl=en-US&gl=US&ceid=US:en", "trust_score": 0.88, "category": "regulator", "adapter": "official", "interval_seconds": 90},
    {"source_id": "doj_rss", "publisher": "DOJ", "url": "https://news.google.com/rss/search?q=site:justice.gov+when:12h&hl=en-US&gl=US&ceid=US:en", "trust_score": 0.86, "category": "regulator", "adapter": "official", "interval_seconds": 90},
    {"source_id": "cisa_rss", "publisher": "CISA", "url": "https://news.google.com/rss/search?q=site:cisa.gov+(advisory+OR+alert+OR+vulnerability)+when:12h&hl=en-US&gl=US&ceid=US:en", "trust_score": 0.84, "category": "regulator", "adapter": "official", "interval_seconds": 90},
    {"source_id": "imf_rss", "publisher": "IMF", "url": "https://news.google.com/rss/search?q=site:imf.org+when:12h&hl=en-US&gl=US&ceid=US:en", "trust_score": 0.90, "category": "regulator", "adapter": "official", "interval_seconds": 90},
    {"source_id": "bis_rss", "publisher": "BIS", "url": "https://news.google.com/rss/search?q=site:bis.org+when:12h&hl=en-US&gl=US&ceid=US:en", "trust_score": 0.88, "category": "regulator", "adapter": "official", "interval_seconds": 120},
    {"source_id": "iea_rss", "publisher": "IEA", "url": "https://news.google.com/rss/search?q=site:iea.org+when:12h&hl=en-US&gl=US&ceid=US:en", "trust_score": 0.86, "category": "research", "interval_seconds": 90},
    {"source_id": "opec_rss", "publisher": "OPEC", "url": "https://news.google.com/rss/search?q=site:opec.org+(oil+OR+production+OR+cut)+when:12h&hl=en-US&gl=US&ceid=US:en", "trust_score": 0.80, "category": "research", "interval_seconds": 120},
    {"source_id": "krebs_rss", "publisher": "Krebs on Security", "url": "https://krebsonsecurity.com/feed/", "trust_score": 0.76, "interval_seconds": 60},
    {"source_id": "bleeping_rss", "publisher": "BleepingComputer", "url": "https://www.bleepingcomputer.com/feed/", "trust_score": 0.64, "interval_seconds": 40},
    {"source_id": "spacenews_rss", "publisher": "SpaceNews", "url": "https://spacenews.com/feed/", "trust_score": 0.70, "interval_seconds": 50},
    {"source_id": "electrek_rss", "publisher": "Electrek", "url": "https://electrek.co/feed/", "trust_score": 0.64, "interval_seconds": 40},
    {"source_id": "macrumors_rss", "publisher": "MacRumors", "url": "https://feeds.macrumors.com/MacRumors-All", "trust_score": 0.62, "interval_seconds": 40},
    {"source_id": "theregister_rss", "publisher": "The Register", "url": "https://www.theregister.com/headlines.atom", "trust_score": 0.64, "adapter": "atom", "interval_seconds": 40},
    {"source_id": "zdnet_rss", "publisher": "ZDNet", "url": "https://www.zdnet.com/news/rss.xml", "trust_score": 0.60, "interval_seconds": 45},
    {"source_id": "tomshardware_rss", "publisher": "Tom's Hardware", "url": "https://www.tomshardware.com/feeds/all", "trust_score": 0.58, "interval_seconds": 45},
    {"source_id": "stat_rss", "publisher": "STAT", "url": "https://www.statnews.com/feed/", "trust_score": 0.76, "interval_seconds": 45},
    {"source_id": "fierce_rss", "publisher": "Fierce Pharma", "url": "https://news.google.com/rss/search?q=site:fiercepharma.com+when:12h&hl=en-US&gl=US&ceid=US:en", "trust_score": 0.70, "interval_seconds": 50},
    {"source_id": "defensenews_rss", "publisher": "Defense News", "url": "https://www.defensenews.com/arc/outboundfeeds/rss/", "trust_score": 0.72, "interval_seconds": 50},
    {"source_id": "freightwaves_rss", "publisher": "FreightWaves", "url": "https://www.freightwaves.com/feed", "trust_score": 0.64, "interval_seconds": 45},
    {"source_id": "utilitydive_rss", "publisher": "Utility Dive", "url": "https://www.utilitydive.com/feeds/news/", "trust_score": 0.64, "interval_seconds": 50},
    {"source_id": "bankingdive_rss", "publisher": "Banking Dive", "url": "https://www.bankingdive.com/feeds/news/", "trust_score": 0.64, "interval_seconds": 50},
    {"source_id": "cyberdive_rss", "publisher": "Cybersecurity Dive", "url": "https://www.cybersecuritydive.com/feeds/news/", "trust_score": 0.62, "interval_seconds": 50},
    {"source_id": "newsbtc_rss", "publisher": "NewsBTC", "url": "https://www.newsbtc.com/feed/", "trust_score": 0.56, "interval_seconds": 30},
    {"source_id": "cryptopotato_rss", "publisher": "CryptoPotato", "url": "https://cryptopotato.com/feed/", "trust_score": 0.56, "interval_seconds": 30},
    {"source_id": "ambcrypto_rss", "publisher": "AMBCrypto", "url": "https://ambcrypto.com/feed/", "trust_score": 0.54, "interval_seconds": 30},
    {"source_id": "coinjournal_rss", "publisher": "CoinJournal", "url": "https://coinjournal.net/feed/", "trust_score": 0.56, "interval_seconds": 30},
    {"source_id": "bitcoinist_rss", "publisher": "Bitcoinist", "url": "https://bitcoinist.com/feed/", "trust_score": 0.52, "interval_seconds": 35},
    {"source_id": "cryptobriefing_rss", "publisher": "CryptoBriefing", "url": "https://cryptobriefing.com/feed/", "trust_score": 0.58, "interval_seconds": 35},
    {"source_id": "forexlive_rss", "publisher": "ForexLive", "url": "https://www.forexlive.com/feed/", "trust_score": 0.64, "interval_seconds": 25},
    {"source_id": "zerohedge_rss", "publisher": "ZeroHedge", "url": "https://news.google.com/rss/search?q=site:zerohedge.com+when:12h&hl=en-US&gl=US&ceid=US:en", "trust_score": 0.42, "interval_seconds": 30},
    {"source_id": "wolfstreet_rss", "publisher": "Wolf Street", "url": "https://wolfstreet.com/feed/", "trust_score": 0.60, "interval_seconds": 50},
    {"source_id": "calculatedrisk_rss", "publisher": "Calculated Risk", "url": "https://www.calculatedriskblog.com/feeds/posts/default", "trust_score": 0.64, "interval_seconds": 60},
    {"source_id": "usatoday_rss", "publisher": "USA Today", "url": "https://news.google.com/rss/search?q=site:usatoday.com+(markets+OR+business)+when:12h&hl=en-US&gl=US&ceid=US:en", "trust_score": 0.68, "interval_seconds": 40},
    {"source_id": "latimes_bus", "publisher": "LA Times Business", "url": "https://www.latimes.com/business/rss2.0.xml", "trust_score": 0.76, "interval_seconds": 45},
    {"source_id": "time_rss", "publisher": "TIME", "url": "https://time.com/feed/", "trust_score": 0.72, "interval_seconds": 45},
    {"source_id": "newsweek_rss", "publisher": "Newsweek", "url": "https://www.newsweek.com/rss", "trust_score": 0.62, "interval_seconds": 45},
    {"source_id": "atlantic_rss", "publisher": "The Atlantic", "url": "https://www.theatlantic.com/feed/all/", "trust_score": 0.78, "interval_seconds": 50},
    {"source_id": "newyorker_rss", "publisher": "New Yorker", "url": "https://www.newyorker.com/feed/news", "trust_score": 0.76, "interval_seconds": 60},
    {"source_id": "project_syndicate", "publisher": "Project Syndicate", "url": "https://www.project-syndicate.org/rss", "trust_score": 0.74, "interval_seconds": 60},
    {"source_id": "vox_rss", "publisher": "Vox", "url": "https://www.vox.com/rss/index.xml", "trust_score": 0.66, "interval_seconds": 45},
    {"source_id": "qz_rss", "publisher": "Quartz", "url": "https://qz.com/rss", "trust_score": 0.70, "interval_seconds": 40},
    {"source_id": "fastcompany_rss", "publisher": "Fast Company", "url": "https://www.fastcompany.com/latest/rss", "trust_score": 0.64, "interval_seconds": 45},
    {"source_id": "inc_rss", "publisher": "Inc", "url": "https://news.google.com/rss/search?q=site:inc.com+when:12h&hl=en-US&gl=US&ceid=US:en", "trust_score": 0.58, "interval_seconds": 50},
    {"source_id": "hbr_rss", "publisher": "HBR", "url": "https://news.google.com/rss/search?q=site:hbr.org+when:12h&hl=en-US&gl=US&ceid=US:en", "trust_score": 0.74, "interval_seconds": 60},
    {"source_id": "mittr_rss", "publisher": "MIT Tech Review", "url": "https://www.technologyreview.com/feed/", "trust_score": 0.78, "interval_seconds": 50},
    {"source_id": "nature_rss", "publisher": "Nature", "url": "https://www.nature.com/nature.rss", "trust_score": 0.86, "category": "research", "interval_seconds": 90},
    {"source_id": "science_rss", "publisher": "Science", "url": "https://www.science.org/rss/news_current.xml", "trust_score": 0.86, "category": "research", "interval_seconds": 90},
]


def _gnews(query: str, hl: str = "en-US", gl: str = "US", ceid: str = "US:en") -> str:
    return f"https://news.google.com/rss/search?q={quote(query)}&hl={hl}&gl={gl}&ceid={ceid}"


def catalog_specs() -> List[Dict]:
    specs: List[Dict] = []
    seen = set()

    def add(item: Dict) -> None:
        sid = item["source_id"]
        if sid in seen:
            return
        seen.add(sid)
        item.setdefault("interval_seconds", 45.0)
        item.setdefault("timeout_seconds", 15.0)
        item.setdefault("max_entries", 12)
        item.setdefault("trust_score", 0.65)
        item.setdefault("category", "media")
        specs.append(item)

    for sid, name, domain, trust in SITES:
        add({
            "source_id": f"gn_{sid}",
            "publisher": name,
            "url": _gnews(f"site:{domain} when:12h"),
            "trust_score": float(trust),
            "interval_seconds": 45.0,
        })
    for sid, name, query, trust in QUERIES:
        add({
            "source_id": sid,
            "publisher": name,
            "url": _gnews(f"({query}) when:12h"),
            "trust_score": float(trust),
            "interval_seconds": 30.0,
            "max_entries": 15,
        })
    for symbol, query in TICKERS:
        add({
            "source_id": f"tkr_{symbol.lower()}",
            "publisher": f"{symbol} news",
            "url": _gnews(f"({query}) (earnings OR listing OR SEC OR hack OR guidance OR ETF OR oil OR rates OR Fed) when:12h"),
            "trust_score": 0.72,
            "interval_seconds": 40.0,
            "max_entries": 10,
        })
    for loc, hl, gl, ceid in LOCALES:
        for topic in TOPICS:
            add({
                "source_id": f"gtopic_{loc}_{topic.lower()}",
                "publisher": f"Google {topic.title()} ({loc.upper()})",
                "url": f"https://news.google.com/rss/headlines/section/topic/{topic}?hl={hl}&gl={gl}&ceid={ceid}",
                "trust_score": 0.70,
                "interval_seconds": 40.0,
            })
        add({
            "source_id": f"ghead_{loc}",
            "publisher": f"Google Headlines ({loc.upper()})",
            "url": f"https://news.google.com/rss?hl={hl}&gl={gl}&ceid={ceid}",
            "trust_score": 0.68,
            "interval_seconds": 35.0,
        })
    for item in DIRECT:
        add(dict(item))
    return specs
